import { sportSlug } from "@/lib/sports/catalog";
import type { CatalogTeam } from "@/lib/sports/types";

type TeamSeed = {
  id?: string;
  name: string;
  league: string;
  leagueId: string;
  country?: string;
};

const LISTS: Record<string, TeamSeed[]> = {
  Soccer: [
    { id: "133604", name: "Arsenal", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133601", name: "Aston Villa", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "134301", name: "Bournemouth", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "134355", name: "Brentford", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133619", name: "Brighton and Hove Albion", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133623", name: "Burnley", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133610", name: "Chelsea", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133632", name: "Crystal Palace", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133615", name: "Everton", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133600", name: "Fulham", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133614", name: "Leeds United", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133602", name: "Liverpool", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133613", name: "Manchester City", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133612", name: "Manchester United", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "134777", name: "Newcastle United", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133847", name: "Nottingham Forest", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133618", name: "Sunderland", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133616", name: "Tottenham", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133636", name: "West Ham United", league: "English Premier League", leagueId: "4328", country: "England" },
    { id: "133611", name: "Wolverhampton Wanderers", league: "English Premier League", leagueId: "4328", country: "England" },

    { id: "133597", name: "Birmingham City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133598", name: "Blackburn Rovers", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133621", name: "Bristol City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133851", name: "Charlton Athletic", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133625", name: "Coventry City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133627", name: "Derby County", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133605", name: "Hull City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133624", name: "Ipswich Town", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133608", name: "Leicester City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133628", name: "Middlesbrough", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133629", name: "Millwall", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133609", name: "Norwich City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133630", name: "Preston North End", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133631", name: "Queens Park Rangers", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133634", name: "Sheffield United", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133635", name: "Sheffield Wednesday", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133617", name: "Southampton", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133638", name: "Stoke City", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133639", name: "Swansea City", league: "English League Championship", leagueId: "4329", country: "Wales" },
    { id: "133620", name: "Watford", league: "English League Championship", leagueId: "4329", country: "England" },
    { id: "133640", name: "West Bromwich Albion", league: "English League Championship", leagueId: "4329", country: "England" },

    { name: "Celtic", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Rangers", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Hearts", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Hibernian", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Aberdeen", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Dundee United", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Kilmarnock", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Motherwell", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "St Mirren", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },
    { name: "Dundee", league: "Scottish Premiership", leagueId: "4330", country: "Scotland" },

    { id: "133727", name: "Athletic Bilbao", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133729", name: "Atletico Madrid", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133739", name: "Barcelona", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133937", name: "Celta Vigo", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "134221", name: "Deportivo Alaves", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "134384", name: "Elche", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133734", name: "Espanyol", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133731", name: "Getafe", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Girona", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133732", name: "Levante", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Mallorca", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Osasuna", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Rayo Vallecano", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Real Betis", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { id: "133738", name: "Real Madrid", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Real Oviedo", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Real Sociedad", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Sevilla", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Valencia", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },
    { name: "Villarreal", league: "Spanish La Liga", leagueId: "4335", country: "Spain" },

    { id: "133667", name: "AC Milan", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "134782", name: "Atalanta", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "134781", name: "Bologna", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "134783", name: "Cagliari", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "134243", name: "Como", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "133674", name: "Fiorentina", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "133675", name: "Genoa", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "133681", name: "Inter Milan", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "133676", name: "Juventus", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Lazio", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Lecce", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { id: "133670", name: "Napoli", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Parma", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Pisa", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Roma", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Sassuolo", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Torino", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Udinese", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Verona", league: "Italian Serie A", leagueId: "4332", country: "Italy" },
    { name: "Cremonese", league: "Italian Serie A", leagueId: "4332", country: "Italy" },

    { id: "133652", name: "Augsburg", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133666", name: "Bayer Leverkusen", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133664", name: "Bayern Munich", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133650", name: "Borussia Dortmund", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "134779", name: "Borussia Monchengladbach", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133814", name: "Eintracht Frankfurt", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133653", name: "Freiburg", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133651", name: "Hamburg", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Heidenheim", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { id: "133657", name: "Hoffenheim", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Koln", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Mainz", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "RB Leipzig", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "St Pauli", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Stuttgart", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Union Berlin", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Werder Bremen", league: "German Bundesliga", leagueId: "4331", country: "Germany" },
    { name: "Wolfsburg", league: "German Bundesliga", leagueId: "4331", country: "Germany" },

    { id: "134709", name: "Angers", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "134788", name: "Auxerre", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133704", name: "Brest", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133862", name: "Le Havre", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133822", name: "Lens", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133711", name: "Lille", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133715", name: "Lorient", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133713", name: "Lyon", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133707", name: "Marseille", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Monaco", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Nantes", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Nice", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { id: "133714", name: "Paris Saint-Germain", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Rennes", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Strasbourg", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Toulouse", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Metz", league: "French Ligue 1", leagueId: "4334", country: "France" },
    { name: "Paris FC", league: "French Ligue 1", leagueId: "4334", country: "France" },

    { id: "133772", name: "Ajax", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { id: "133767", name: "AZ Alkmaar", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { id: "133758", name: "Feyenoord", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { id: "134304", name: "Go Ahead Eagles", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { id: "133762", name: "Groningen", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { id: "133759", name: "Heerenveen", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "PSV", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "Sparta Rotterdam", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "Twente", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "Utrecht", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "NEC Nijmegen", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },
    { name: "Fortuna Sittard", league: "Dutch Eredivisie", leagueId: "4337", country: "Netherlands" },

    { id: "134108", name: "Benfica", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { id: "134098", name: "Braga", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { name: "Porto", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { id: "135708", name: "Sporting CP", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { name: "Vitoria Guimaraes", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { id: "134387", name: "Arouca", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { id: "138864", name: "Casa Pia", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { id: "134106", name: "Estoril Praia", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { name: "Moreirense", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },
    { name: "Rio Ave", league: "Portuguese Primeira Liga", leagueId: "4344", country: "Portugal" },

    { name: "Inter Miami", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "LAFC", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "LA Galaxy", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Atlanta United", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Seattle Sounders", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "New York City FC", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "New York Red Bulls", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Columbus Crew", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "FC Cincinnati", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Philadelphia Union", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Austin FC", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "FC Dallas", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Houston Dynamo", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Portland Timbers", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Vancouver Whitecaps", league: "Major League Soccer", leagueId: "4346", country: "Canada" },
    { name: "Toronto FC", league: "Major League Soccer", leagueId: "4346", country: "Canada" },
    { name: "CF Montreal", league: "Major League Soccer", leagueId: "4346", country: "Canada" },
    { name: "Chicago Fire", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Orlando City", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Nashville SC", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Minnesota United", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Real Salt Lake", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Sporting Kansas City", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Colorado Rapids", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "San Jose Earthquakes", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "Charlotte FC", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "DC United", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "New England Revolution", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "St. Louis City", league: "Major League Soccer", leagueId: "4346", country: "USA" },
    { name: "San Diego FC", league: "Major League Soccer", leagueId: "4346", country: "USA" },

    { id: "134299", name: "Atletico Mineiro", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { id: "134293", name: "Bahia", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { id: "134285", name: "Botafogo", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { id: "134736", name: "Bragantino", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { id: "134284", name: "Corinthians", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Cruzeiro", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Flamengo", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Fluminense", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Gremio", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Internacional", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Palmeiras", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Santos", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Sao Paulo", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },
    { name: "Vasco da Gama", league: "Brazilian Serie A", leagueId: "4351", country: "Brazil" },

    { name: "Boca Juniors", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "River Plate", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Racing Club", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Independiente", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "San Lorenzo", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Estudiantes", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Velez Sarsfield", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Huracan", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Lanus", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },
    { name: "Talleres", league: "Argentine Primera Division", leagueId: "4406", country: "Argentina" },

    { name: "Shanghai Port", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Shanghai Shenhua", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Beijing Guoan", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Shandong Taishan", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Chengdu Rongcheng", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Zhejiang", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Tianjin Jinmen Tiger", league: "Chinese Super League", leagueId: "4359", country: "China" },
    { name: "Wuhan Three Towns", league: "Chinese Super League", leagueId: "4359", country: "China" },

    { name: "Kashima Antlers", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Urawa Red Diamonds", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Yokohama F. Marinos", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Kawasaki Frontale", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Gamba Osaka", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Cerezo Osaka", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Sanfrecce Hiroshima", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Nagoya Grampus", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "FC Tokyo", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Vissel Kobe", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Albirex Niigata", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },
    { name: "Avispa Fukuoka", league: "Japanese J1 League", leagueId: "4633", country: "Japan" },

    { id: "138113", name: "Gimcheon Sangmu", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { id: "138109", name: "Gwangju FC", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { id: "138110", name: "Incheon United", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { id: "139078", name: "Jeju SK", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { id: "138111", name: "Jeonbuk Hyundai Motors", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Ulsan HD", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Pohang Steelers", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "FC Seoul", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Suwon FC", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Daejeon Hana Citizen", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Daegu FC", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },
    { name: "Gangwon FC", league: "South Korean K League 1", leagueId: "4689", country: "South Korea" },

    { name: "Al-Hilal", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Nassr", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Ahli", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Ittihad", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Ettifaq", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Shabab", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Qadsiah", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },
    { name: "Al-Fateh", league: "Saudi Pro League", leagueId: "4668", country: "Saudi Arabia" },

    { name: "Kitchee", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Lee Man", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Eastern", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Tai Po", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Hong Kong Rangers", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Southern District", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "HKFC", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "Kowloon City", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },
    { name: "North District", league: "Hong Kong Premier League", leagueId: "4825", country: "Hong Kong" },

    { name: "Club America", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Chivas Guadalajara", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Cruz Azul", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Pumas UNAM", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Monterrey", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Tigres UANL", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Toluca", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Santos Laguna", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Pachuca", league: "Liga MX", leagueId: "4350", country: "Mexico" },
    { name: "Leon", league: "Liga MX", leagueId: "4350", country: "Mexico" },

    { name: "Galatasaray", league: "Turkish Super Lig", leagueId: "4339", country: "Turkey" },
    { name: "Fenerbahce", league: "Turkish Super Lig", leagueId: "4339", country: "Turkey" },
    { name: "Besiktas", league: "Turkish Super Lig", leagueId: "4339", country: "Turkey" },
    { name: "Trabzonspor", league: "Turkish Super Lig", leagueId: "4339", country: "Turkey" },

    { name: "Club Brugge", league: "Belgian Pro League", leagueId: "4338", country: "Belgium" },
    { name: "Anderlecht", league: "Belgian Pro League", leagueId: "4338", country: "Belgium" },
    { name: "Genk", league: "Belgian Pro League", leagueId: "4338", country: "Belgium" },
    { name: "Antwerp", league: "Belgian Pro League", leagueId: "4338", country: "Belgium" },
    { name: "Standard Liege", league: "Belgian Pro League", leagueId: "4338", country: "Belgium" },

    { name: "Melbourne Victory", league: "Australian A-League", leagueId: "4356", country: "Australia" },
    { name: "Sydney FC", league: "Australian A-League", leagueId: "4356", country: "Australia" },
    { name: "Melbourne City", league: "Australian A-League", leagueId: "4356", country: "Australia" },
    { name: "Western Sydney Wanderers", league: "Australian A-League", leagueId: "4356", country: "Australia" },
    { name: "Auckland FC", league: "Australian A-League", leagueId: "4356", country: "New Zealand" },
    { name: "Macarthur FC", league: "Australian A-League", leagueId: "4356", country: "Australia" },

    { name: "Orlando Pride", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Kansas City Current", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Portland Thorns", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "North Carolina Courage", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "San Diego Wave", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Washington Spirit", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Gotham FC", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Seattle Reign", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Angel City", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Houston Dash", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Utah Royals", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Racing Louisville", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Bay FC", league: "NWSL", leagueId: "4521", country: "USA" },
    { name: "Chicago Stars", league: "NWSL", leagueId: "4521", country: "USA" },
  ],
  Basketball: [
    { id: "134880", name: "Atlanta Hawks", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134860", name: "Boston Celtics", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134861", name: "Brooklyn Nets", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134881", name: "Charlotte Hornets", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134870", name: "Chicago Bulls", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134871", name: "Cleveland Cavaliers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134875", name: "Dallas Mavericks", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134885", name: "Denver Nuggets", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134872", name: "Detroit Pistons", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134865", name: "Golden State Warriors", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134876", name: "Houston Rockets", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134873", name: "Indiana Pacers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134866", name: "Los Angeles Clippers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134867", name: "Los Angeles Lakers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134877", name: "Memphis Grizzlies", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134882", name: "Miami Heat", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134874", name: "Milwaukee Bucks", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134886", name: "Minnesota Timberwolves", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134878", name: "New Orleans Pelicans", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134862", name: "New York Knicks", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134887", name: "Oklahoma City Thunder", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134883", name: "Orlando Magic", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134863", name: "Philadelphia 76ers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134888", name: "Phoenix Suns", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134889", name: "Portland Trail Blazers", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134890", name: "Sacramento Kings", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134879", name: "San Antonio Spurs", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134864", name: "Toronto Raptors", league: "NBA", leagueId: "4387", country: "Canada" },
    { id: "134891", name: "Utah Jazz", league: "NBA", leagueId: "4387", country: "USA" },
    { id: "134884", name: "Washington Wizards", league: "NBA", leagueId: "4387", country: "USA" },

    { id: "136447", name: "Atlanta Dream", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136440", name: "Chicago Sky", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136445", name: "Connecticut Sun", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136441", name: "Dallas Wings", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "150722", name: "Golden State Valkyries", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136439", name: "Indiana Fever", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136437", name: "Las Vegas Aces", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136443", name: "Los Angeles Sparks", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136442", name: "Minnesota Lynx", league: "WNBA", leagueId: "4516", country: "USA" },
    { id: "136438", name: "New York Liberty", league: "WNBA", leagueId: "4516", country: "USA" },
    { name: "Phoenix Mercury", league: "WNBA", leagueId: "4516", country: "USA" },
    { name: "Seattle Storm", league: "WNBA", leagueId: "4516", country: "USA" },
    { name: "Washington Mystics", league: "WNBA", leagueId: "4516", country: "USA" },

    { id: "135435", name: "Beijing Ducks", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { id: "137339", name: "Beijing Royal Fighters", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { id: "135440", name: "Guangdong Southern Tigers", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { id: "135444", name: "Liaoning Flying Leopards", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { id: "135443", name: "Jilin Northeast Tigers", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { name: "Xinjiang Flying Tigers", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { name: "Zhejiang Lions", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { name: "Shanghai Sharks", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { name: "Shenzhen Leopards", league: "Chinese CBA", leagueId: "4442", country: "China" },
    { name: "Guangzhou Loong Lions", league: "Chinese CBA", leagueId: "4442", country: "China" },

    { name: "Real Madrid Basketball", league: "EuroLeague Basketball", leagueId: "4546", country: "Spain" },
    { name: "FC Barcelona Basketball", league: "EuroLeague Basketball", leagueId: "4546", country: "Spain" },
    { name: "Olympiacos", league: "EuroLeague Basketball", leagueId: "4546", country: "Greece" },
    { name: "Panathinaikos", league: "EuroLeague Basketball", leagueId: "4546", country: "Greece" },
    { name: "Fenerbahce Beko", league: "EuroLeague Basketball", leagueId: "4546", country: "Turkey" },
    { name: "Anadolu Efes", league: "EuroLeague Basketball", leagueId: "4546", country: "Turkey" },
    { name: "AS Monaco Basketball", league: "EuroLeague Basketball", leagueId: "4546", country: "France" },
  ],
  "American Football": [
    { id: "134946", name: "Arizona Cardinals", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134942", name: "Atlanta Falcons", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134922", name: "Baltimore Ravens", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134918", name: "Buffalo Bills", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134943", name: "Carolina Panthers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134938", name: "Chicago Bears", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134923", name: "Cincinnati Bengals", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134924", name: "Cleveland Browns", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134934", name: "Dallas Cowboys", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134930", name: "Denver Broncos", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134939", name: "Detroit Lions", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134940", name: "Green Bay Packers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134926", name: "Houston Texans", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134927", name: "Indianapolis Colts", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134928", name: "Jacksonville Jaguars", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134931", name: "Kansas City Chiefs", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134932", name: "Las Vegas Raiders", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "135908", name: "Los Angeles Chargers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "135907", name: "Los Angeles Rams", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134919", name: "Miami Dolphins", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134941", name: "Minnesota Vikings", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134920", name: "New England Patriots", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134944", name: "New Orleans Saints", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134935", name: "New York Giants", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134921", name: "New York Jets", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134936", name: "Philadelphia Eagles", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134925", name: "Pittsburgh Steelers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134948", name: "San Francisco 49ers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134949", name: "Seattle Seahawks", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134945", name: "Tampa Bay Buccaneers", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134929", name: "Tennessee Titans", league: "NFL", leagueId: "4391", country: "USA" },
    { id: "134937", name: "Washington Commanders", league: "NFL", leagueId: "4391", country: "USA" },
  ],
  Baseball: [
    { id: "135267", name: "Arizona Diamondbacks", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135261", name: "Athletics", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135268", name: "Atlanta Braves", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135251", name: "Baltimore Orioles", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135252", name: "Boston Red Sox", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135269", name: "Chicago Cubs", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135253", name: "Chicago White Sox", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135270", name: "Cincinnati Reds", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135254", name: "Cleveland Guardians", league: "MLB", leagueId: "4424", country: "USA" },
    { id: "135271", name: "Colorado Rockies", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Detroit Tigers", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Houston Astros", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Kansas City Royals", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Los Angeles Angels", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Los Angeles Dodgers", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Miami Marlins", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Milwaukee Brewers", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Minnesota Twins", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "New York Mets", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "New York Yankees", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Philadelphia Phillies", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Pittsburgh Pirates", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "San Diego Padres", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "San Francisco Giants", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Seattle Mariners", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "St. Louis Cardinals", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Tampa Bay Rays", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Texas Rangers", league: "MLB", leagueId: "4424", country: "USA" },
    { name: "Toronto Blue Jays", league: "MLB", leagueId: "4424", country: "Canada" },
    { name: "Washington Nationals", league: "MLB", leagueId: "4424", country: "USA" },

    { name: "Yomiuri Giants", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Hanshin Tigers", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "SoftBank Hawks", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Hiroshima Toyo Carp", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Chunichi Dragons", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Yakult Swallows", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Orix Buffaloes", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Seibu Lions", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Chiba Lotte Marines", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Rakuten Golden Eagles", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Nippon-Ham Fighters", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },
    { name: "Yokohama DeNA BayStars", league: "Nippon Baseball League", leagueId: "4591", country: "Japan" },

    { name: "Kia Tigers", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "LG Twins", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "Doosan Bears", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "Samsung Lions", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "SSG Landers", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "KT Wiz", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "NC Dinos", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "Lotte Giants", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "Hanwha Eagles", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
    { name: "Kiwoom Heroes", league: "Korean KBO League", leagueId: "4830", country: "South Korea" },
  ],
  "Ice Hockey": [
    { id: "134846", name: "Anaheim Ducks", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134830", name: "Boston Bruins", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134831", name: "Buffalo Sabres", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134848", name: "Calgary Flames", league: "NHL", leagueId: "4380", country: "Canada" },
    { id: "134838", name: "Carolina Hurricanes", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134854", name: "Chicago Blackhawks", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134855", name: "Colorado Avalanche", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134839", name: "Columbus Blue Jackets", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134856", name: "Dallas Stars", league: "NHL", leagueId: "4380", country: "USA" },
    { id: "134832", name: "Detroit Red Wings", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Edmonton Oilers", league: "NHL", leagueId: "4380", country: "Canada" },
    { name: "Florida Panthers", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Los Angeles Kings", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Minnesota Wild", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Montreal Canadiens", league: "NHL", leagueId: "4380", country: "Canada" },
    { name: "Nashville Predators", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "New Jersey Devils", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "New York Islanders", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "New York Rangers", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Ottawa Senators", league: "NHL", leagueId: "4380", country: "Canada" },
    { name: "Philadelphia Flyers", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Pittsburgh Penguins", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "San Jose Sharks", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Seattle Kraken", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "St. Louis Blues", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Tampa Bay Lightning", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Toronto Maple Leafs", league: "NHL", leagueId: "4380", country: "Canada" },
    { name: "Utah Hockey Club", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Vancouver Canucks", league: "NHL", leagueId: "4380", country: "Canada" },
    { name: "Vegas Golden Knights", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Washington Capitals", league: "NHL", leagueId: "4380", country: "USA" },
    { name: "Winnipeg Jets", league: "NHL", leagueId: "4380", country: "Canada" },
  ],
  Motorsport: [
    { id: "135126", name: "Aston Martin Aramco Formula One Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "137569", name: "Audi Revolut F1 Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "135706", name: "BWT Alpine Formula One Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "154529", name: "Cadillac Formula 1 Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "134811", name: "McLaren Formula 1 Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "134812", name: "Mercedes-AMG PETRONAS Formula One Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "135705", name: "MoneyGram Haas F1 Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "134813", name: "Oracle Red Bull Racing", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "134806", name: "Scuderia Ferrari HP", league: "Formula 1", leagueId: "4370", country: "World" },
    { id: "139631", name: "Visa Cash App Racing Bulls Formula One Team", league: "Formula 1", leagueId: "4370", country: "World" },
    { name: "Williams Racing", league: "Formula 1", leagueId: "4370", country: "World" },
    { name: "Ducati Lenovo Team", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Aprilia Racing", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Monster Energy Yamaha MotoGP", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Repsol Honda Team", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Red Bull KTM Factory Racing", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Gresini Racing MotoGP", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "VR46 Racing Team", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Trackhouse MotoGP Team", league: "MotoGP", leagueId: "4407", country: "World" },
    { name: "Hendrick Motorsports", league: "NASCAR Cup Series", leagueId: "4393", country: "USA" },
    { name: "Joe Gibbs Racing", league: "NASCAR Cup Series", leagueId: "4393", country: "USA" },
    { name: "Team Penske", league: "NASCAR Cup Series", leagueId: "4393", country: "USA" },
    { name: "23XI Racing", league: "NASCAR Cup Series", leagueId: "4393", country: "USA" },
  ],
  Rugby: [
    { name: "Leinster", league: "United Rugby Championship", leagueId: "4446", country: "Ireland" },
    { name: "Munster", league: "United Rugby Championship", leagueId: "4446", country: "Ireland" },
    { name: "Ulster", league: "United Rugby Championship", leagueId: "4446", country: "Ireland" },
    { name: "Connacht", league: "United Rugby Championship", leagueId: "4446", country: "Ireland" },
    { name: "Glasgow Warriors", league: "United Rugby Championship", leagueId: "4446", country: "Scotland" },
    { name: "Edinburgh", league: "United Rugby Championship", leagueId: "4446", country: "Scotland" },
    { name: "Stormers", league: "United Rugby Championship", leagueId: "4446", country: "South Africa" },
    { name: "Bulls", league: "United Rugby Championship", leagueId: "4446", country: "South Africa" },
    { name: "Sharks", league: "United Rugby Championship", leagueId: "4446", country: "South Africa" },
    { name: "Lions", league: "United Rugby Championship", leagueId: "4446", country: "South Africa" },
    { name: "Cardiff", league: "United Rugby Championship", leagueId: "4446", country: "Wales" },
    { name: "Ospreys", league: "United Rugby Championship", leagueId: "4446", country: "Wales" },
    { name: "Scarlets", league: "United Rugby Championship", leagueId: "4446", country: "Wales" },
    { name: "Toulouse", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Bordeaux Begles", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Racing 92", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Stade Francais", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "La Rochelle", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Toulon", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Clermont", league: "French Top 14", leagueId: "4430", country: "France" },
    { name: "Saracens", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Leicester Tigers", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Northampton Saints", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Bath", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Harlequins", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Sale Sharks", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Bristol Bears", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Exeter Chiefs", league: "English Premiership Rugby", leagueId: "4414", country: "England" },
    { name: "Crusaders", league: "Super Rugby", leagueId: "4551", country: "New Zealand" },
    { name: "Blues", league: "Super Rugby", leagueId: "4551", country: "New Zealand" },
    { name: "Chiefs", league: "Super Rugby", leagueId: "4551", country: "New Zealand" },
    { name: "Hurricanes", league: "Super Rugby", leagueId: "4551", country: "New Zealand" },
    { name: "Brumbies", league: "Super Rugby", leagueId: "4551", country: "Australia" },
    { name: "Queensland Reds", league: "Super Rugby", leagueId: "4551", country: "Australia" },
    { name: "Melbourne Storm", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Penrith Panthers", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Sydney Roosters", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Brisbane Broncos", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Canterbury Bulldogs", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "South Sydney Rabbitohs", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Parramatta Eels", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "North Queensland Cowboys", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Cronulla Sharks", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Manly Sea Eagles", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Newcastle Knights", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Canberra Raiders", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Wests Tigers", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "St George Illawarra Dragons", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Gold Coast Titans", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "Dolphins", league: "National Rugby League", leagueId: "4416", country: "Australia" },
    { name: "New Zealand Warriors", league: "National Rugby League", leagueId: "4416", country: "New Zealand" },
  ],
  "Australian Football": [
    { name: "Adelaide Crows", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Brisbane Lions", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Carlton", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Collingwood", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Essendon", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Fremantle", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Geelong Cats", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Gold Coast Suns", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "GWS Giants", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Hawthorn", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Melbourne", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "North Melbourne", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Port Adelaide", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Richmond", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "St Kilda", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Sydney Swans", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "West Coast Eagles", league: "Australian AFL", leagueId: "4456", country: "Australia" },
    { name: "Western Bulldogs", league: "Australian AFL", leagueId: "4456", country: "Australia" },
  ],
  Cricket: [
    { name: "Mumbai Indians", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Chennai Super Kings", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Royal Challengers Bengaluru", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Kolkata Knight Riders", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Sunrisers Hyderabad", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Delhi Capitals", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Rajasthan Royals", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Punjab Kings", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Gujarat Titans", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Lucknow Super Giants", league: "Indian Premier League", leagueId: "4460", country: "India" },
    { name: "Sydney Sixers", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Sydney Thunder", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Melbourne Stars", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Melbourne Renegades", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Perth Scorchers", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Brisbane Heat", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Adelaide Strikers", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
    { name: "Hobart Hurricanes", league: "Australian Big Bash League", leagueId: "4461", country: "Australia" },
  ],
  Esports: [
    { name: "T1", league: "League of Legends Champions Korea", leagueId: "4529", country: "South Korea" },
    { name: "Gen.G", league: "League of Legends Champions Korea", leagueId: "4529", country: "South Korea" },
    { name: "Hanwha Life Esports", league: "League of Legends Champions Korea", leagueId: "4529", country: "South Korea" },
    { name: "Dplus KIA", league: "League of Legends Champions Korea", leagueId: "4529", country: "South Korea" },
    { name: "KT Rolster", league: "League of Legends Champions Korea", leagueId: "4529", country: "South Korea" },
    { name: "JD Gaming", league: "League of Legends Pro League", leagueId: "4528", country: "China" },
    { name: "Bilibili Gaming", league: "League of Legends Pro League", leagueId: "4528", country: "China" },
    { name: "Top Esports", league: "League of Legends Pro League", leagueId: "4528", country: "China" },
    { name: "LNG Esports", league: "League of Legends Pro League", leagueId: "4528", country: "China" },
    { name: "Weibo Gaming", league: "League of Legends Pro League", leagueId: "4528", country: "China" },
    { name: "G2 Esports", league: "League of Legends EMEA Championship", leagueId: "4530", country: "Europe" },
    { name: "Fnatic", league: "League of Legends EMEA Championship", leagueId: "4530", country: "Europe" },
    { name: "Movistar KOI", league: "League of Legends EMEA Championship", leagueId: "4530", country: "Europe" },
    { name: "Natus Vincere", league: "BLAST Premier", leagueId: "5426", country: "World" },
    { name: "Team Vitality", league: "BLAST Premier", leagueId: "5426", country: "World" },
    { name: "FaZe Clan", league: "BLAST Premier", leagueId: "5426", country: "World" },
    { name: "MOUZ", league: "BLAST Premier", leagueId: "5426", country: "World" },
    { name: "The MongolZ", league: "BLAST Premier", leagueId: "5426", country: "World" },
    { name: "FURIA", league: "BLAST Premier", leagueId: "5426", country: "World" },
  ],
  Volleyball: [
    { name: "Modena Volley", league: "Italian Volleyball League", leagueId: "4544", country: "Italy" },
    { name: "Trentino Volley", league: "Italian Volleyball League", leagueId: "4544", country: "Italy" },
    { name: "Perugia", league: "Italian Volleyball League", leagueId: "4544", country: "Italy" },
    { name: "Lube Civitanova", league: "Italian Volleyball League", leagueId: "4544", country: "Italy" },
    { name: "ZAKSA", league: "Polish PlusLiga", leagueId: "5619", country: "Poland" },
    { name: "Jastrzebski Wegiel", league: "Polish PlusLiga", leagueId: "5619", country: "Poland" },
  ],
  Handball: [
    { name: "THW Kiel", league: "German Handball-Bundesliga", leagueId: "4533", country: "Germany" },
    { name: "SC Magdeburg", league: "German Handball-Bundesliga", leagueId: "4533", country: "Germany" },
    { name: "Fuchse Berlin", league: "German Handball-Bundesliga", leagueId: "4533", country: "Germany" },
    { name: "FC Barcelona Handball", league: "Spanish Liga ASOBAL", leagueId: "4534", country: "Spain" },
    { name: "Paris Saint-Germain Handball", league: "French LNH Division 1", leagueId: "4536", country: "France" },
    { name: "Montpellier Handball", league: "French LNH Division 1", leagueId: "4536", country: "France" },
  ],
};

function toTeam(sport: string, seed: TeamSeed): CatalogTeam {
  return {
    id: seed.id || `${sportSlug(sport)}-${sportSlug(seed.name)}`,
    name: seed.name,
    sport,
    league: seed.league,
    leagueId: seed.leagueId,
    country: seed.country,
  };
}

export function popularTeamsForSport(sport: string): CatalogTeam[] {
  return (LISTS[sport] ?? []).map((seed) => toTeam(sport, seed));
}

export function popularTeamsForLeague(leagueId: string): CatalogTeam[] {
  const teams: CatalogTeam[] = [];
  for (const [sport, seeds] of Object.entries(LISTS)) {
    for (const seed of seeds) {
      if (seed.leagueId === leagueId) teams.push(toTeam(sport, seed));
    }
  }
  return teams;
}

export function popularTeamGroups(sport: string): Array<{ league: string; leagueId?: string; teams: CatalogTeam[] }> {
  const groups: Array<{ league: string; leagueId?: string; teams: CatalogTeam[] }> = [];
  for (const team of popularTeamsForSport(sport)) {
    const current = groups.find((group) => group.league === team.league);
    if (current) current.teams.push(team);
    else groups.push({ league: team.league ?? sport, leagueId: team.leagueId, teams: [team] });
  }
  return groups;
}
