import { lookupName, normalizeKey } from "@/lib/i18n/names";
import { sportSlug } from "@/lib/sports/catalog";
import type { CatalogAthlete } from "@/lib/sports/types";

const LISTS: Record<string, string[]> = {
  Soccer: [
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Erling Haaland",
    "Kylian Mbappe",
    "Mohamed Salah",
    "Jude Bellingham",
    "Vinicius Junior",
    "Harry Kane",
    "Son Heung-min",
    "Kevin De Bruyne",
    "Lamine Yamal",
    "Bukayo Saka",
    "Pedri",
    "Rodri",
    "Robert Lewandowski",
    "Lautaro Martinez",
    "Victor Osimhen",
    "Florian Wirtz",
    "Jamal Musiala",
    "Phil Foden",
    "Declan Rice",
    "Cole Palmer",
    "Rodrygo",
    "Federico Valverde",
    "Thibaut Courtois",
    "Alisson",
    "Gianluigi Donnarumma",
    "Neymar",
    "Ousmane Dembele",
    "Antoine Griezmann",
  ],
  Basketball: [
    "LeBron James",
    "Stephen Curry",
    "Nikola Jokic",
    "Luka Doncic",
    "Kevin Durant",
    "Giannis Antetokounmpo",
    "Jayson Tatum",
    "Shai Gilgeous-Alexander",
    "Anthony Edwards",
    "Joel Embiid",
    "Kawhi Leonard",
    "Jimmy Butler",
    "Damian Lillard",
    "Victor Wembanyama",
    "Anthony Davis",
    "Kyrie Irving",
    "Ja Morant",
    "Jalen Brunson",
    "Devin Booker",
    "Trae Young",
    "Donovan Mitchell",
    "Tyrese Haliburton",
    "Paolo Banchero",
    "Zion Williamson",
    "Karl-Anthony Towns",
    "Bam Adebayo",
    "Jaylen Brown",
    "Cade Cunningham",
    "LaMelo Ball",
    "Chet Holmgren",
  ],
  "American Football": [
    "Patrick Mahomes",
    "Josh Allen",
    "Lamar Jackson",
    "Joe Burrow",
    "Jalen Hurts",
    "Justin Herbert",
    "Dak Prescott",
    "CeeDee Lamb",
    "Tyreek Hill",
    "Justin Jefferson",
    "Ja'Marr Chase",
    "Travis Kelce",
    "Christian McCaffrey",
    "Saquon Barkley",
    "Derrick Henry",
    "Micah Parsons",
    "T.J. Watt",
    "Nick Bosa",
    "Myles Garrett",
    "Fred Warner",
    "Brock Purdy",
    "CJ Stroud",
    "Jayden Daniels",
    "Amon-Ra St. Brown",
    "A.J. Brown",
    "Stefon Diggs",
    "Davante Adams",
    "George Kittle",
    "Tua Tagovailoa",
    "Aaron Rodgers",
  ],
  Baseball: [
    "Shohei Ohtani",
    "Aaron Judge",
    "Mookie Betts",
    "Ronald Acuna Jr",
    "Juan Soto",
    "Freddie Freeman",
    "Jose Altuve",
    "Mike Trout",
    "Bryce Harper",
    "Francisco Lindor",
    "Fernando Tatis Jr",
    "Yordan Alvarez",
    "Bobby Witt Jr",
    "Gunnar Henderson",
    "Elly De La Cruz",
    "Julio Rodriguez",
    "Corey Seager",
    "Manny Machado",
    "Rafael Devers",
    "Vladimir Guerrero Jr",
    "Paul Skenes",
    "Gerrit Cole",
    "Yoshinobu Yamamoto",
    "Tarik Skubal",
    "Corbin Burnes",
    "Max Scherzer",
    "Clayton Kershaw",
    "Kodai Senga",
    "Cal Raleigh",
    "Ketel Marte",
  ],
  "Ice Hockey": [
    "Connor McDavid",
    "Nathan MacKinnon",
    "Auston Matthews",
    "Leon Draisaitl",
    "Nikita Kucherov",
    "Cale Makar",
    "Sidney Crosby",
    "Alexander Ovechkin",
    "David Pastrnak",
    "Kirill Kaprizov",
    "Jack Hughes",
    "Matthew Tkachuk",
    "Mikko Rantanen",
    "Quinn Hughes",
    "Adam Fox",
    "Igor Shesterkin",
    "Andrei Vasilevskiy",
    "Connor Hellebuyck",
    "William Nylander",
    "Mitch Marner",
    "Brayden Point",
    "Elias Pettersson",
    "Tim Stutzle",
    "Connor Bedard",
    "Macklin Celebrini",
    "Aleksander Barkov",
    "Artemi Panarin",
    "Victor Hedman",
    "Roman Josi",
    "Steven Stamkos",
  ],
  Motorsport: [
    "Max Verstappen",
    "Lewis Hamilton",
    "Lando Norris",
    "Charles Leclerc",
    "Oscar Piastri",
    "George Russell",
    "Carlos Sainz",
    "Fernando Alonso",
    "Sergio Perez",
    "Pierre Gasly",
    "Esteban Ocon",
    "Alexander Albon",
    "Yuki Tsunoda",
    "Nico Hulkenberg",
    "Lance Stroll",
    "Andrea Kimi Antonelli",
    "Oliver Bearman",
    "Isack Hadjar",
    "Liam Lawson",
    "Franco Colapinto",
    "Marc Marquez",
    "Francesco Bagnaia",
    "Jorge Martin",
    "Fabio Quartararo",
    "Pedro Acosta",
    "Enea Bastianini",
    "Alex Marquez",
    "Marco Bezzecchi",
    "Brad Binder",
    "Maverick Vinales",
  ],
  Tennis: [
    "Carlos Alcaraz",
    "Jannik Sinner",
    "Novak Djokovic",
    "Alexander Zverev",
    "Daniil Medvedev",
    "Taylor Fritz",
    "Holger Rune",
    "Casper Ruud",
    "Stefanos Tsitsipas",
    "Andrey Rublev",
    "Ben Shelton",
    "Jack Draper",
    "Alex de Minaur",
    "Tommy Paul",
    "Hubert Hurkacz",
    "Iga Swiatek",
    "Aryna Sabalenka",
    "Coco Gauff",
    "Qinwen Zheng",
    "Elena Rybakina",
    "Jessica Pegula",
    "Madison Keys",
    "Jasmine Paolini",
    "Mirra Andreeva",
    "Naomi Osaka",
    "Ons Jabeur",
    "Barbora Krejcikova",
    "Marketa Vondrousova",
    "Emma Navarro",
    "Amanda Anisimova",
  ],
  Golf: [
    "Scottie Scheffler",
    "Rory McIlroy",
    "Xander Schauffele",
    "Jon Rahm",
    "Viktor Hovland",
    "Collin Morikawa",
    "Ludvig Aberg",
    "Patrick Cantlay",
    "Wyndham Clark",
    "Max Homa",
    "Tommy Fleetwood",
    "Shane Lowry",
    "Justin Thomas",
    "Jordan Spieth",
    "Brooks Koepka",
    "Bryson DeChambeau",
    "Hideki Matsuyama",
    "Sungjae Im",
    "Tony Finau",
    "Sahith Theegala",
    "Cameron Smith",
    "Joaquin Niemann",
    "Min Woo Lee",
    "Nelly Korda",
    "Lydia Ko",
    "Jin Young Ko",
    "Rose Zhang",
    "Charley Hull",
    "Ruoning Yin",
    "Hannah Green",
  ],
  Cycling: [
    "Tadej Pogacar",
    "Jonas Vingegaard",
    "Remco Evenepoel",
    "Primoz Roglic",
    "Wout van Aert",
    "Mathieu van der Poel",
    "Mads Pedersen",
    "Jasper Philipsen",
    "Tim Merlier",
    "Biniam Girmay",
    "Tom Pidcock",
    "Julian Alaphilippe",
    "Egan Bernal",
    "Geraint Thomas",
    "Adam Yates",
    "Simon Yates",
    "Enric Mas",
    "Carlos Rodriguez",
    "Juan Ayuso",
    "Isaac del Toro",
    "Demi Vollering",
    "Lotte Kopecky",
    "Katarzyna Niewiadoma",
    "Elisa Longo Borghini",
    "Marianne Vos",
    "Pauline Ferrand-Prevot",
    "Lorena Wiebes",
    "Chloe Dygert",
    "Anna van der Breggen",
    "Annemiek van Vleuten",
  ],
  Rugby: [
    "Antoine Dupont",
    "Ardie Savea",
    "Eben Etzebeth",
    "Siya Kolisi",
    "Beauden Barrett",
    "Richie Mo'unga",
    "Will Jordan",
    "Rieko Ioane",
    "Jordie Barrett",
    "Cheslin Kolbe",
    "Damian Willemse",
    "Handre Pollard",
    "Owen Farrell",
    "Maro Itoje",
    "Finn Russell",
    "Huw Jones",
    "Louis Rees-Zammit",
    "Marcus Smith",
    "Johnny Sexton",
    "Caelan Doris",
    "Josh van der Flier",
    "Bundee Aki",
    "Thomas Ramos",
    "Damian Penaud",
    "Romain Ntamack",
    "Malcolm Marx",
    "Pieter-Steph du Toit",
    "Scott Barrett",
    "Codie Taylor",
    "Sam Cane",
  ],
  "Australian Football": [
    "Nick Daicos",
    "Marcus Bontempelli",
    "Christian Petracca",
    "Clayton Oliver",
    "Patrick Cripps",
    "Jeremy Cameron",
    "Charlie Curnow",
    "Tom Hawkins",
    "Toby Greene",
    "Isaac Heeney",
    "Chad Warner",
    "Errol Gulden",
    "Zak Butters",
    "Connor Rozee",
    "Sam Walsh",
    "Andrew Brayshaw",
    "Hugh McCluggage",
    "Touk Miller",
    "Max Gawn",
    "Brodie Grundy",
    "Jack Steele",
    "Tim Taranto",
    "Shai Bolton",
    "Bailey Smith",
    "Jamarra Ugle-Hagan",
    "Harley Reid",
    "Matt Rowell",
    "Noah Anderson",
    "Caleb Serong",
    "Izak Rankine",
  ],
  Cricket: [
    "Virat Kohli",
    "Rohit Sharma",
    "Jasprit Bumrah",
    "MS Dhoni",
    "Hardik Pandya",
    "Suryakumar Yadav",
    "KL Rahul",
    "Shubman Gill",
    "Rishabh Pant",
    "Ravindra Jadeja",
    "Pat Cummins",
    "Steve Smith",
    "David Warner",
    "Travis Head",
    "Mitchell Starc",
    "Josh Hazlewood",
    "Kane Williamson",
    "Trent Boult",
    "Rachin Ravindra",
    "Ben Stokes",
    "Joe Root",
    "Harry Brook",
    "Jofra Archer",
    "Jos Buttler",
    "Babar Azam",
    "Shaheen Afridi",
    "Shakib Al Hasan",
    "Rashid Khan",
    "Kagiso Rabada",
    "Quinton de Kock",
  ],
  Fighting: [
    "Islam Makhachev",
    "Ilia Topuria",
    "Alex Pereira",
    "Jon Jones",
    "Israel Adesanya",
    "Leon Edwards",
    "Sean O'Malley",
    "Max Holloway",
    "Alexander Volkanovski",
    "Charles Oliveira",
    "Dustin Poirier",
    "Justin Gaethje",
    "Tom Aspinall",
    "Ciryl Gane",
    "Khabib Nurmagomedov",
    "Conor McGregor",
    "Zhang Weili",
    "Valentina Shevchenko",
    "Amanda Nunes",
    "Dricus du Plessis",
    "Merab Dvalishvili",
    "Arman Tsarukyan",
    "Shavkat Rakhmonov",
    "Francis Ngannou",
    "Canelo Alvarez",
    "Tyson Fury",
    "Oleksandr Usyk",
    "Terence Crawford",
    "Naoya Inoue",
    "Gervonta Davis",
  ],
  Esports: [
    "Faker",
    "Chovy",
    "Knight",
    "Ruler",
    "TheShy",
    "Rookie",
    "Caps",
    "Canyon",
    "Keria",
    "Zeus",
    "Gumayusi",
    "Uzi",
    "ShowMaker",
    "Bin",
    "JackeyLove",
    "s1mple",
    "ZywOo",
    "NiKo",
    "donk",
    "m0NESY",
    "device",
    "sh1ro",
    "Twistzz",
    "yuurih",
    "KSCERATO",
    "broky",
    "frozen",
    "ropz",
    "EliGE",
    "FalleN",
  ],
  Volleyball: [
    "Wilfredo Leon",
    "Matt Anderson",
    "Nimir Abdel-Aziz",
    "Earvin Ngapeth",
    "Yuki Ishikawa",
    "Yuji Nishida",
    "Ran Takahashi",
    "Torey DeFalco",
    "Wallace de Souza",
    "Ricardo Lucarelli",
    "Bruno Rezende",
    "Osmany Juantorena",
    "Ivan Zaytsev",
    "Simone Giannelli",
    "Alessandro Michieletto",
    "Paola Egonu",
    "Tijana Boskovic",
    "Zhu Ting",
    "Gabriela Guimaraes",
    "Michelle Bartsch-Hackley",
    "Andrea Drews",
    "Kim Yeon-koung",
    "Elena Pietrini",
    "Isabelle Haak",
    "Mayu Ishikawa",
    "Kelsey Robinson",
    "Foluke Akinradewo",
    "Yuan Xinyue",
    "Li Yingying",
    "Zhang Changning",
  ],
  Handball: [
    "Mikkel Hansen",
    "Nikola Karabatic",
    "Sander Sagosen",
    "Niklas Landin",
    "Domagoj Duvnjak",
    "Luc Steins",
    "Mathias Gidsel",
    "Dika Mem",
    "Nedim Remili",
    "Ludovic Fabregas",
    "Kentin Mahe",
    "Andreas Wolff",
    "Uwe Gensheimer",
    "Aron Palmarsson",
    "Jim Gottfridsson",
    "Hampus Wanne",
    "Emil Nielsen",
    "Luka Cindric",
    "Kiril Lazarov",
    "Rodrigo Corrales",
    "Vincent Gerard",
    "Henrik Toft Hansen",
    "Kamil Syprzak",
    "Alex Dujshebaev",
    "Casper Ulrich Mortensen",
    "Hans Lindberg",
    "Rasmus Lauge",
    "Gedeon Guardiola",
    "Jannick Green",
    "Niklas Ekberg",
  ],
  Darts: [
    "Michael van Gerwen",
    "Luke Humphries",
    "Luke Littler",
    "Gerwyn Price",
    "Peter Wright",
    "Gary Anderson",
    "Rob Cross",
    "Michael Smith",
    "Nathan Aspinall",
    "Dimitri Van den Bergh",
    "Jonny Clayton",
    "James Wade",
    "Dave Chisnall",
    "Joe Cullen",
    "Stephen Bunting",
    "Chris Dobey",
    "Andrew Gilding",
    "Ross Smith",
    "Dirk van Duijvenbode",
    "Danny Noppert",
    "Raymond van Barneveld",
    "Phil Taylor",
    "Adrian Lewis",
    "Simon Whitlock",
    "Mensur Suljovic",
    "Krzysztof Ratajski",
    "Josh Rock",
    "Ryan Searle",
    "Martin Schindler",
    "Ricardo Pietreczko",
  ],
  Snooker: [
    "Ronnie O'Sullivan",
    "Judd Trump",
    "Mark Selby",
    "Shaun Murphy",
    "John Higgins",
    "Mark Williams",
    "Neil Robertson",
    "Kyren Wilson",
    "Luca Brecel",
    "Ding Junhui",
    "Zhao Xintong",
    "Yan Bingtao",
    "Zhang Anda",
    "Si Jiahui",
    "Pang Junxu",
    "Ali Carter",
    "Jack Lisowski",
    "Barry Hawkins",
    "Hossein Vafaei",
    "Gary Wilson",
    "Ryan Day",
    "Zhou Yuelong",
    "Xiao Guodong",
    "Thepchaiya Un-Nooh",
    "Anthony McGill",
    "Stuart Bingham",
    "Jimmy White",
    "Stephen Hendry",
    "Mark Allen",
    "Liang Wenbo",
  ],
  "Field Hockey": [
    "Alexander Hendrickx",
    "Tom Boon",
    "Arthur Van Doren",
    "Vincent Vanasch",
    "Florent van Aubel",
    "John-John Dohmen",
    "Thierry Brinkman",
    "Jorrit Croon",
    "Lars Balk",
    "Mirco Pruyser",
    "Billy Bakker",
    "Harmanpreet Singh",
    "Manpreet Singh",
    "PR Sreejesh",
    "Hardik Singh",
    "Mandeep Singh",
    "Lalremsiami",
    "Vandana Katariya",
    "Gonzalo Peillat",
    "Lucas Vila",
    "Agustin Mazzilli",
    "Matias Rey",
    "Jeremy Hayward",
    "Jake Harvie",
    "Tim Brand",
    "Blake Govers",
    "Eddie Ockenden",
    "Kieran Govers",
    "Christopher Ruhr",
    "Mats Grambusch",
  ],
  Athletics: [
    "Noah Lyles",
    "Letsile Tebogo",
    "Kishane Thompson",
    "Sha'Carri Richardson",
    "Shericka Jackson",
    "Sydney McLaughlin-Levrone",
    "Femke Bol",
    "Mondo Duplantis",
    "Jakob Ingebrigtsen",
    "Josh Kerr",
    "Grant Holloway",
    "Karsten Warholm",
    "Ryan Crouser",
    "Neeraj Chopra",
    "Faith Kipyegon",
    "Sifan Hassan",
    "Eliud Kipchoge",
    "Kelvin Kiptum",
    "Jacob Kiplimo",
    "Soufiane El Bakkali",
    "Winfred Yavi",
    "Yulimar Rojas",
    "Katie Moon",
    "Tara Davis-Woodhall",
    "Quincy Hall",
    "Gabby Thomas",
    "Melissa Jefferson",
    "Zharnel Hughes",
    "Fred Kerley",
    "Erriyon Knighton",
  ],
  Badminton: [
    "Viktor Axelsen",
    "Anders Antonsen",
    "Kodai Naraoka",
    "Li Shifeng",
    "Shi Yuqi",
    "Jonatan Christie",
    "Anthony Sinisuka Ginting",
    "Lakshya Sen",
    "Kunlavut Vitidsarn",
    "Loh Kean Yew",
    "Lee Zii Jia",
    "Chou Tien-chen",
    "Kento Momota",
    "An Se-young",
    "Chen Yufei",
    "Tai Tzu-ying",
    "Carolina Marin",
    "Akane Yamaguchi",
    "Wang Zhiyi",
    "Han Yue",
    "PV Sindhu",
    "Gregoria Mariska Tunjung",
    "Zheng Siwei",
    "Huang Yaqiong",
    "Chen Qingchen",
    "Jia Yifan",
    "Seo Seung-jae",
    "Chae Yoo-jung",
    "Kim Won-ho",
    "Dechapol Puavaranukroh",
  ],
  "Table Tennis": [
    "Fan Zhendong",
    "Wang Chuqin",
    "Ma Long",
    "Xu Xin",
    "Liang Jingkun",
    "Lin Gaoyuan",
    "Lin Shidong",
    "Hugo Calderano",
    "Truls Moregard",
    "Darko Jorgic",
    "Tomokazu Harimoto",
    "Shunsuke Togami",
    "Jang Woojin",
    "Lim Jonghoon",
    "Alexis Lebrun",
    "Felix Lebrun",
    "Sun Yingsha",
    "Chen Meng",
    "Wang Manyu",
    "Chen Xingtong",
    "Wang Yidi",
    "Mima Ito",
    "Hina Hayata",
    "Miu Hirano",
    "Shin Yubin",
    "Jeon Jihee",
    "Bernadette Szocs",
    "Sofia Polcanova",
    "Yuan Licen",
    "Kuai Man",
  ],
  Netball: [
    "Jhaniele Fowler-Nembhard",
    "Maria Folau",
    "Caitlin Bassett",
    "Gretel Bueta",
    "Liz Watson",
    "Paige Hadley",
    "Jamie-Lee Price",
    "Sunday Aryang",
    "Donnell Wallam",
    "Sophie Garbin",
    "Helen Housby",
    "Jo Harten",
    "Geva Mentor",
    "Serena Guthrie",
    "Natalie Haythornthwaite",
    "Sulu Fitzpatrick",
    "Ameliaranne Ekenasio",
    "Gina Crampton",
    "Jane Watson",
    "Karin Burger",
    "Grace Nweke",
    "Kate Lloyd",
    "Shimona Nelson",
    "Mwai Kumwenda",
    "Joyce Mvula",
    "Tharina Snyman",
    "Lenize Potgieter",
    "Khanyisa Chawane",
    "Bongiwe Msomi",
    "Irene van Dyk",
  ],
  Skiing: [
    "Marco Odermatt",
    "Mikaela Shiffrin",
    "Lara Gut-Behrami",
    "Sofia Goggia",
    "Federica Brignone",
    "Petra Vlhova",
    "Henrik Kristoffersen",
    "Lucas Braathen",
    "Loic Meillard",
    "Marco Schwarz",
    "Aleksander Aamodt Kilde",
    "Vincent Kriechmayr",
    "Lindsey Vonn",
    "Wendy Holdener",
    "Camille Rast",
    "Johannes Thingnes Boe",
    "Sturla Holm Laegreid",
    "Quentin Fillon Maillet",
    "Ingrid Landmark Tandrevold",
    "Ryoyu Kobayashi",
    "Stefan Kraft",
    "Halvor Egner Granerud",
    "Anze Lanisek",
    "Gyda Westvold Hansen",
    "Jarl Magnus Riiber",
    "Therese Johaug",
    "Johannes Hoesflot Klaebo",
    "Jessie Diggins",
    "Frida Karlsson",
    "Johannes Strolz",
  ],
  Skating: [
    "Ilia Malinin",
    "Yuzuru Hanyu",
    "Shoma Uno",
    "Nathan Chen",
    "Yuma Kagiyama",
    "Mikhail Shaidorov",
    "Adam Siao Him Fa",
    "Jason Brown",
    "Cha Jun-hwan",
    "Kao Miura",
    "Kaori Sakamoto",
    "Loena Hendrickx",
    "Isabeau Levito",
    "Amber Glenn",
    "Kim Chae-yeon",
    "Mone Chiba",
    "Wakaba Higuchi",
    "Alysa Liu",
    "Kim Yuna",
    "Evgenia Medvedeva",
    "Alina Zagitova",
    "Anna Shcherbakova",
    "Mao Asada",
    "Evgeni Plushenko",
    "Patrick Chan",
    "Javier Fernandez",
    "Madison Chock",
    "Evan Bates",
    "Piper Gilles",
    "Paul Poirier",
  ],
  Wintersports: [
    "Brad Gushue",
    "Niklas Edin",
    "Bruce Mouat",
    "Yannick Schwaller",
    "Joanne Courtney",
    "Rachel Homan",
    "Silvana Tirinzoni",
    "Anna Hasselborg",
    "Eve Muirhead",
    "Jennifer Jones",
    "Kevin Koe",
    "Brendan Bottcher",
    "Ross Whyte",
    "Magnus Ramsfjell",
    "Korey Dropkin",
    "John Shuster",
    "Tabitha Peterson",
    "Nina Roth",
    "Alina Paetz",
    "Agnes Knochenhauer",
    "Sara McManus",
    "Sofia Mabergs",
    "Kerri Einarson",
    "Val Sweeting",
    "Shannon Birchard",
    "Briane Harris",
    "Gim Eun-ji",
    "Kim Eun-jung",
    "Satsuki Fujisawa",
    "Chinami Yoshida",
  ],
  Watersports: [
    "Katie Ledecky",
    "Caeleb Dressel",
    "Leon Marchand",
    "Summer McIntosh",
    "Pan Zhanle",
    "Zhang Yufei",
    "Wang Shun",
    "Qin Haiyang",
    "Adam Peaty",
    "Sarah Sjostrom",
    "Kaylee McKeown",
    "Ariarne Titmus",
    "Mollie O'Callaghan",
    "David Popovici",
    "Kristof Milak",
    "Thomas Ceccon",
    "Kyle Chalmers",
    "Emma McKeon",
    "Michael Phelps",
    "Sun Yang",
    "Ye Shiwen",
    "Quan Hongchan",
    "Chen Yuxi",
    "Xie Siyi",
    "Cao Yuan",
    "Yang Hao",
    "Zhang Jiaqi",
    "Filip Filipovic",
    "Pietro Figlioli",
    "Ashleigh Johnson",
  ],
  "Multi Sports": [
    "Alex Yee",
    "Hayden Wilde",
    "Kristian Blummenfelt",
    "Cassandre Beaugrand",
    "Beth Potter",
    "Taylor Knibb",
    "Flora Duffy",
    "Georgia Taylor-Brown",
    "Vincent Luis",
    "Jonny Brownlee",
    "Alistair Brownlee",
    "Mario Mola",
    "Javier Gomez Noya",
    "Magnus Ditlev",
    "Sam Laidlow",
    "Lionel Sanders",
    "Lucy Charles-Barclay",
    "Daniela Ryf",
    "Jan Frodeno",
    "Patrick Lange",
    "Gustav Iden",
    "Laura Philipp",
    "Taylor Spivey",
    "Morgan Pearson",
    "Gwen Jorgensen",
    "Nicola Spirig",
    "Damian Hall",
    "Tim Don",
    "Henri Schoeman",
    "Seth Rider",
  ],
  Gaelic: [
    "David Clifford",
    "Shane Walsh",
    "Sean O'Shea",
    "Conor McKenna",
    "Brian Fenton",
    "James McCarthy",
    "Stephen Cluxton",
    "Ciaran Kilkenny",
    "Paul Mannion",
    "Dean Rock",
    "Michael Murphy",
    "Patrick McBrearty",
    "Shane McGuigan",
    "Rian O'Neill",
    "Con O'Callaghan",
    "Brian Hurley",
    "Cian Lynch",
    "Aaron Gillane",
    "Gearoid Hegarty",
    "Kyle Hayes",
    "Tony Kelly",
    "TJ Reid",
    "Eoin Cody",
    "Patrick Horgan",
    "Diarmaid Byrnes",
    "Nickie Quaid",
    "Seamus Flanagan",
    "Cillian McDaid",
    "Shane O'Donnell",
    "John Conlon",
  ],
};

function toAthlete(sport: string, name: string): CatalogAthlete {
  return {
    id: `${sportSlug(sport)}-${sportSlug(name)}`,
    name,
    sport,
  };
}

export function popularAthletesForSport(sport: string): CatalogAthlete[] {
  const names = LISTS[sport] ?? [];
  return names.slice(0, 30).map((name) => toAthlete(sport, name));
}

export function searchPopularAthletes(query: string): CatalogAthlete[] {
  const needle = normalizeKey(query);
  if (needle.length < 2) return [];
  const hits: CatalogAthlete[] = [];
  for (const [sport, names] of Object.entries(LISTS)) {
    for (const name of names) {
      const pair = lookupName(name);
      const blob = normalizeKey([name, sport, pair?.hant, pair?.hans].filter(Boolean).join(" "));
      if (blob.includes(needle)) hits.push(toAthlete(sport, name));
      if (hits.length >= 12) return hits;
    }
  }
  return hits;
}
